---
sudo: false
language: python

env:
- EC2_REGION=eu-central-1 BOTO_CONFIG="/dev/null"

services:
- docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
- pip install molecule
- pip install docker-py

# install Google Cloud related packages
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
# Decrypt Google Cloud Platform service account json key file
- openssl aes-256-cbc -K $encrypted_c0be5bd8086d_key -iv $encrypted_c0be5bd8086d_iv -in testproject-233213-45d56e1b7fc5.json.enc -out testproject-233213-45d56e1b7fc5.json -d
# Authenticate against GCP with decrypted key file
- gcloud auth activate-service-account --key-file testproject-233213-45d56e1b7fc5.json
  # Set GCP project id
- gcloud config set project $GCP_GCE_PROJECT_ID
  # Generate GCP ssh files
- gcloud compute ssh gcp-gce-ubuntu

# install AWS related packages
- pip install boto boto3
- pip install --upgrade awscli
# configure AWS CLI
- aws configure set aws_access_key_id $AWS_ACCESS_KEY
- aws configure set aws_secret_access_key $AWS_SECRET_KEY
- aws configure set default.region $DEPLOYMENT_REGION
# show AWS CLI config
- aws configure list

script:
- cd docker
# Molecule Testing Travis-locally with Docker
#- molecule test
# Molecule Testing on AWS EC2
#- molecule create --scenario-name aws-ec2-ubuntu
#- molecule converge --scenario-name aws-ec2-ubuntu
#- molecule verify --scenario-name aws-ec2-ubuntu
#- molecule destroy --scenario-name aws-ec2-ubuntu
# Run Molecule test on GCP
- molecule test --scenario-name gcp-gce-ubuntu