---
sudo: false
language: python

env:
- EC2_REGION=eu-central-1 BOTO_CONFIG="/dev/null"

services:
- docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
- pip install molecule
- pip install docker-py

# install Google Cloud related packages
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version

# install AWS related packages
- pip install boto boto3
- pip install --upgrade awscli
# configure AWS CLI
- aws configure set aws_access_key_id $AWS_ACCESS_KEY
- aws configure set aws_secret_access_key $AWS_SECRET_KEY
- aws configure set default.region $DEPLOYMENT_REGION
# show AWS CLI config
- aws configure list

script:
- cd docker
# Molecule Testing Travis-locally with Docker
#- molecule test
# Molecule Testing on AWS EC2
#- molecule create --scenario-name aws-ec2-ubuntu
#- molecule converge --scenario-name aws-ec2-ubuntu
#- molecule verify --scenario-name aws-ec2-ubuntu
#- molecule destroy --scenario-name aws-ec2-ubuntu