---
sudo: false
language: python

env:
- GCE_CREDENTIALS_FILE=$TRAVIS_BUILD_DIR/testproject-233213-45d56e1b7fc5.json GCE_SERVICE_ACCOUNT_EMAIL=molecule@testproject-233213.iam.gserviceaccount.com GCE_PROJECT_ID=testproject-233213

services:
- docker

cache: pip

install:
- pip install molecule
- pip install docker-py
- pip install gcloud apache-libcloud pycrypto

# Was gcloud CLI successfully installed?
- gcloud version
# Decrypt Google Cloud Platform service account json key file
- openssl aes-256-cbc -K $encrypted_c0be5bd8086d_key -iv $encrypted_c0be5bd8086d_iv -in testproject-233213-45d56e1b7fc5.json.enc -out testproject-233213-45d56e1b7fc5.json -d
# Authenticate against GCP with decrypted key file
- gcloud auth activate-service-account --key-file testproject-233213-45d56e1b7fc5.json
  # Set GCP project id
- gcloud config set project $GCP_GCE_PROJECT_ID

script:
- cd docker
# Molecule Testing Travis-locally with Docker
#- molecule test
# Run Molecule test on GCP
- molecule --debug create --scenario-name gcp-gce-ubuntu
- molecule --debug converge --scenario-name gcp-gce-ubuntu
- molecule --debug verify --scenario-name gcp-gce-ubuntu
- molecule --debug destroy --scenario-name gcp-gce-ubuntu